<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <BaseOutputPath>$(SolutionDir)bin\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\**" />
    <EmbeddedResource Remove="Components\**" />
    <None Remove="Components\**" />
    <Page Remove="Components\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flow.Core\Flow.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Style\" />
  </ItemGroup>

</Project>
